wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1630459676
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      4: 3.9.0
      5: 0.12.1
      8:
      - 5
batch_size:
  desc: null
  value: 4
beta1:
  desc: null
  value: 0.0
beta2:
  desc: null
  value: 0.99
checkpoint_dir:
  desc: null
  value: expr/checkpoints/celeba_hq
custom_out_img:
  desc: null
  value: starganv2_cross_celeba.jpg
custom_ref:
  desc: null
  value: assets/representative/celeba_hq/ref
custom_src:
  desc: null
  value: assets/representative/celeba_hq/src
ds_iter:
  desc: null
  value: 100000
eval_dir:
  desc: null
  value: expr/eval
eval_every:
  desc: null
  value: 10000
extend_domain:
  desc: null
  value: 1
f_lr:
  desc: null
  value: 1.0e-06
hidden_dim:
  desc: null
  value: 512
img_size:
  desc: null
  value: 256
inp_dir:
  desc: null
  value: assets/representative/custom/female
lambda_cyc:
  desc: null
  value: 1.0
lambda_ds:
  desc: null
  value: 1.0
lambda_reg:
  desc: null
  value: 1.0
lambda_sty:
  desc: null
  value: 1.0
latent_dim:
  desc: null
  value: 16
lm_path:
  desc: null
  value: expr/checkpoints/celeba_lm_mean.npz
lr:
  desc: null
  value: 0.0001
mode:
  desc: null
  value: train
model_name:
  desc: null
  value: ''
num_domains:
  desc: null
  value: 2
num_outs_per_domain:
  desc: null
  value: 10
num_workers:
  desc: null
  value: 4
out_dir:
  desc: null
  value: assets/representative/celeba_hq/src/female
print_every:
  desc: null
  value: 10
randcrop_prob:
  desc: null
  value: 0.5
ref_dir:
  desc: null
  value: assets/representative/celeba_hq/ref
result_dir:
  desc: null
  value: expr/results
resume_iter:
  desc: null
  value: 0
sample_dir:
  desc: null
  value: expr/samples
sample_every:
  desc: null
  value: 2000
save_every:
  desc: null
  value: 5000
seed:
  desc: null
  value: 777
src_dir:
  desc: null
  value: assets/representative/celeba_hq/src
style_dim:
  desc: null
  value: 64
total_iters:
  desc: null
  value: 1000
train_img_dir:
  desc: null
  value: data/celeba_hq/train
val_batch_size:
  desc: null
  value: 32
val_img_dir:
  desc: null
  value: data/celeba_hq/val
w_hpf:
  desc: null
  value: 1.0
weight_decay:
  desc: null
  value: 0.0001
wing_path:
  desc: null
  value: expr/checkpoints/wing.ckpt
